### ISSUE TITLE
Add 16px version

### ISSUE THREAD

**Issue by felixfbecker** [daveLK/windows-git-folder-icon#1]
It would be nice if the icons (.ico only of course) had a 16px version so they fit the other folder's style in quick launch in explorer (Windows 10).

![image](https://cloud.githubusercontent.com/assets/10532611/12480805/4db6e254-c045-11e5-88ef-c69ac5d8a0b3.png)

**Comment by daveLK** [comment]
A new commit has been pushed. There should be 16px versions of the icons in the ico file now.

**Comment by felixfbecker** [comment]
My icon still looks the same. Did you just scale down the icon? What I meant was that it would be nice to have a custom version for the 16px version that looks like the other folder icons you can see in the screenshot. How do you make your ico files?

**Comment by daveLK** [comment]
I used [this website](http://icoconvert.com/image_to_icon_converter/) to create it. Was that the right method to create it?

**Comment by felixfbecker** [comment]
Ah ok. Don't worry, it's awesome you put it on Github, I love to customize my folders.

The website allows you to upload multiple icons with different resolutions and they will all get into the ico. So if you upload one image with 16x16 and one with 256x256, the 16x16 version will be used in Windows for the example above and that can be a totally different icon instead of just scaled down :)

**Comment by daveLK** [comment]
Ah, I see. Are there other better tools to use out there? This was the first result that popped up for me so I gave it a try.

**Comment by felixfbecker** [comment]
I don't know. Back in the XP days I used a shareware called GConvert but that is ancient now. I think the online converter should do it just fine?

**Comment by daveLK** [comment]
Oh Ok, thanks!

**Comment by daveLK** [comment]
The new icons have been added. I created multiple versions of the icon of different sizes, with 16px being just the git icon, and combined them into one .ico file using a web tool. Hope it works now!

**Comment by felixfbecker** [comment]
@daveLK Awesome work! But it seems like I was wrong because apparently explorer uses the 24px version for the sidebar. Could you make that the git icon only too?

**Comment by daveLK** [comment]
Ok, sure! I'm on it.

**Comment by daveLK** [comment]
I've pushed the new version. It should work now.

**Comment by felixfbecker** [comment]
It looks awesome!
